# -*- coding: utf-8 -*-
"""netflix_movies.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ks4ZuisFNdixoKuU5a_FTXUSST3WS27Z
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the data (change the file name to whatever you downloaded)
df = pd.read_csv('netflix_titles.csv')

# Look at the first 5 rows to see what you are dealing with
print(df.head())

# Look at the overall shape (rows, columns)
print(df.shape)

# 1. Check for missing values in every column
print(df.isnull().sum())

# 2. Check the datatypes (are numberes stored as text? Are dats stored as strings?)
print(df.dtypes)

# 3. Check for duplicate rows
print(df.duplicated().sum())

# 4. Look at the unique values in a text column to seee if these are typos
print(df['country'].unique()) #You will probably see 'United States' , 'USA' , 'US' - all meaning the same thing!

import pandas as pd
df = pd.read_csv('netflix_titles.csv')
# 1. Handle Missing Values (Option A: Drop them , Option B: Fill them)
# If a row is missing the Director, let's fill it with the unkown
df['director'] = df['director'].fillna('Unknown') # Removed inplace=True and reassigned

#If a row is missing the rating, let's drop thta row entirely (because we need that for analysis)
df.dropna(subset=['rating'], inplace=True)

# 2. Fix inconsitent text (Standaridze country names)
# replace 'USA' and 'US' with 'United States'
df['country'] = df['country'].replace(['USA', 'US'] , 'United States')

# 3. Convert a text date into an actual Date Format
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce') # Added errors='coerce'

# 4. Extract useful info from text(Split a column)
# The duration of Column might say '90min' or '2season'. Lets extrat jusatg the number
df['duration_int'] = df['duration'].str.extract(r'(\d+)').fillna(0).astype(float)

# verify your cleaning worked
print(df.info())

# ========================================================================
# Step 4: Feature Engineering (Creating New Knowledge)
# ========================================================================

# 1. Split the 'cast' column to count how many actors are in each movie
df['num_of_actors'] = df['cast'].str.split(',').str.len().fillna(0).astype(int)

# 2. extract the year from the 'date_added' column to see trends over time
df['year_added'] = df['date_added'].dt.year

# 3. Extract the month from 'date_added ' (useful for sesonal anlysis)
df['month_added'] = df['date_added'].dt.month

# 4. Create a 'decade' column tom group movies (1960s,1970s, etc )
df['decade'] = (df['release_year'] // 10) * 10

# 5. Crreate a Bniary flag: Is this movie from Usa or not?/
df['is_usa'] = np.where(df['country'] == 'United States',1,0)

# 6. Create a 'genre_simple' column (extract first genre only)
df['genre_simple'] = df['listed_in'].str.split(',').str[0]

# 7. Check if title contains specific keywords (for fun analysis)
df['has_netflix_in_title'] = df['title'].str.contains('Netflix' , case=False).astype(int)

# Display the new columns
print("\n Newly created columns:")
print(df[['title', 'num_of_actors' , 'year_added' , "month_added" , "decade" , 'is_usa' ,'genre_simple']].head(10))

# Show summary statistics of the new columns:")
print(df[['num_of_actors' , 'duration_int' , 'year_added']].describe())

#

# Set a nice visual style
sns.set_style('whitegrid')

# ---------Chart 1: What rating (PG, R, TV-MA) is most commmon?--------
plt.figure(figsize=(10,6))
sns.countplot(y=df['rating'], order=df['rating'].value_counts().index[:10])
plt.title('Top 10 Most Common Content Ratings on Netflix')
plt.tight_layout()
plt.savefig('rating_distribution.png') #Save your Chart!
plt.show()

# ---------Chart 2: Does adding moviees to Netflix change by year?-------
plt.figure(figsize=(12,6))
df['year_added'].value_counts().sort_index().plot(kind='line',marker = 'o')
plt.title('Number of Titles Added to Netflix Over the Years')
plt.xlabel('Year')
plt.ylabel('Count of Titles')
plt.savefig('trend_over_time.png')
plt.show()

# ----------Chart 3: Are movies getting shorter or longer over time?-------

plt.figure(figsize=(12,6))
sns.scatterplot(x='release_year' , y='duration_int' , data=df, alpha=0.4)
plt.title('MOvie Runtime vs Release Year')
plt.savefig('runtime_over_time.png')
plt.show()

# -----------Chart 4: Heatmap of missing data (to show off)----------
plt.figure(figsize=(10,6))
sns.heatmap(df.isnull() , cbar=False, yticklabels=False, cmap='viridis')
plt.title('Where is our Data misding?')
plt.savefig('missing_data.png')
plt.show()

# ---------Chart 5: Top 10 Countries with Most Content
plt.figure(figsize=(12,6))
df['country'].value_counts().head(10).plot(kind='bar')
plt.title('Top 10 Countries Producing Netflix Content')
plt.xlabel('Number of Titles')
plt.tight_layout()
plt.savefig('top_countries.png')
plt.show()

# -----------Chart 6: Movies vs TV shows over Time (Stacked Bar)
df_grouped = df.groupby(['year_added' , 'type']).size().unstack()
df_grouped.plot(kind = 'bar' , stacked = True, figsize=(14,6))
plt.title('MOvies vs Tv Shows Addded to Netflix Each Year')
plt.ylabel('Count')
plt.tight_layout()
plt.savefig('movies_vs_tv.png')
plt.show()

# ---------------Chart 7: Duration Distribution (Movies Only)

movies = df[df['type'] == 'Movie']
plt.figure(figsize=(12,6))
sns.histplot(movies['duration_int'].dropna(),bins=30,kde=True)
plt.title('Distribution of Movie Runtimes on Netflix')
plt.xlabel('Minutes')
plt.savefig('runtime_distribution.png')
plt.show()

